#include "vfvector2.h"

const VFVECTOR2 VFVECTOR2::ORIGIN( 0 , 0 ) ;
const VFVECTOR2 VFVECTOR2::ZERO( 0 , 0 ) ;
const VFVECTOR2 VFVECTOR2::AXIS_X( 1 , 0 ) ;
const VFVECTOR2 VFVECTOR2::AXIS_Y( 0 , 1 ) ; 
const VFVECTOR2 VFVECTOR2::AXIS_NEG_X( -1 , 0 ) ;
const VFVECTOR2 VFVECTOR2::AXIS_NEG_Y( 0 , -1 ) ; 
const VFVECTOR2 VFVECTOR2::UNIT_SCALE( 1 , 1 );
const VFVECTOR2 VFVECTOR2::VTBL[] = { VFVECTOR2::AXIS_X , VFVECTOR2::AXIS_Y } ; 