#include "vfvector3.h"

const VFVECTOR3 VFVECTOR3::ORIGIN( 0 , 0 , 0 ) ;
const VFVECTOR3 VFVECTOR3::ZERO( 0 , 0 , 0 ) ;
const VFVECTOR3 VFVECTOR3::AXIS_X( 1 , 0 , 0 ) ;
const VFVECTOR3 VFVECTOR3::AXIS_Y( 0 , 1 , 0 ) ;
const VFVECTOR3 VFVECTOR3::AXIS_Z( 0 , 0 , 1 ) ;
const VFVECTOR3 VFVECTOR3::AXIS_NEG_X( -1 , 0 , 0 ) ;
const VFVECTOR3 VFVECTOR3::AXIS_NEG_Y( 0 , -1 , 0 ) ;
const VFVECTOR3 VFVECTOR3::AXIS_NEG_Z( 0 , 0 , -1 ) ;
const VFVECTOR3 VFVECTOR3::UNIT_SCALE( 1 , 1 , 1 );
const VFVECTOR3 VFVECTOR3::VTBL[] = { VFVECTOR3::AXIS_X , VFVECTOR3::AXIS_Y , VFVECTOR3::AXIS_Z } ;
const VFVECTOR3 VFVECTOR3::NEG_VTBL[] = { VFVECTOR3::AXIS_NEG_X , VFVECTOR3::AXIS_NEG_Y , VFVECTOR3::AXIS_NEG_Z } ;
const VFVECTOR3 VFVECTOR3::DIR_VTBL[] = { VFVECTOR3::AXIS_X , VFVECTOR3::AXIS_Y , VFVECTOR3::AXIS_Z
                                        , VFVECTOR3::AXIS_NEG_X , VFVECTOR3::AXIS_NEG_Y , VFVECTOR3::AXIS_NEG_Z } ;
